[project]
name = "ahmed-yahya-ai"
version = "0.1.0"
description = "مكتبة خوارزميات الذكاء الاصطناعي من تطوير أحمد يحيى"
authors = [
    { name="Ahmed Yahya", email="ahmed.yahya@example.com" }
]
readme = "README.md"
requires-python = ">=3.8"
license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence"
]
dependencies = [
    "numpy>=1.24.0",
    "scikit-learn>=1.2.0",
    "pandas>=1.5.0"
]
[project.urls]
"Homepage" = "https://github.com/Hmodyyahya735/ahmed-yahya-ai"
"Bug Tracker" = "https://github.com/Hmodyyahya735/ahmed-yahya-ai/issues"
[tool.setuptools]
packages = ["ahmed_yahya_ai"]
package-dir = {"" = "src"}